import {createRequire} from 'node:module';
import {resolve} from 'node:path';
import {mkdir} from 'node:fs/promises';
import assert from 'node:assert/strict';
import {normalizeSave,chooseStarter,makeUnit,maxHP,ZONES,PATROL_IDS} from '../dist/world.js';
const {chromium}=createRequire(resolve(process.argv[2],'../package.json'))('playwright');
const browser=await chromium.launch({channel:'chrome',headless:true,args:['--use-fake-device-for-media-stream','--use-fake-ui-for-media-stream']});
await mkdir('output/qa-v2',{recursive:true});
const allErrors=[];
const watch=page=>{page.on('pageerror',e=>allErrors.push(e.message));page.on('response',r=>{if(r.status()>=400)allErrors.push(`${r.status()} ${r.url()}`);});};
const ready=page=>page.waitForFunction(()=>document.querySelector('#game').dataset.phase==='ready');
const loaded=page=>page.locator('#loader').waitFor({state:'hidden'});
const saved=page=>page.evaluate(()=>JSON.parse(localStorage.getItem('woodbadge-quest-v2')));
try{
  const context=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:2,isMobile:true,hasTouch:true,acceptDownloads:true});
  const page=await context.newPage();watch(page);await page.goto('http://127.0.0.1:4173/');await loaded(page);
  await page.screenshot({path:'output/qa-v2/starter.png'});
  await page.locator('[data-action="starter"][data-arg="beaver"]').click();
  assert.equal((await saved(page)).team[0],'beaver');
  await page.screenshot({path:'output/qa-v2/trail.png'});
  await page.locator('[data-action="zone"][data-arg="1"]').click();
  assert.match(await page.locator('#world-toast').textContent(),/Fellowship/);
  await page.locator('[data-action="explore"]').click();await ready(page);
  assert.equal(await page.locator('#encounter-name').textContent(),'Bobwhite');
  await page.screenshot({path:'output/qa-v2/bobwhite-encounter.png'});
  await page.locator('#berry-button').click();assert.equal((await saved(page)).berries,11);
  await page.evaluate(()=>{Math.random=()=>0;});
  await page.locator('#ball-button').click();
  const cdp=await context.newCDPSession(page),ball=await page.locator('#throw-button').boundingBox();
  const x=ball.x+ball.width/2,y=ball.y+ball.height/2;
  await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y}]});
  for(let i=1;i<=6;i++)await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x,y:y-i*28}]});
  await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
  await page.locator('#result-dialog').waitFor({state:'visible'});
  assert.match(await page.locator('#result-subtitle').textContent(),/Bobwhite/);
  assert.equal((await saved(page)).roster.length,2);
  await page.locator('#next-button').click();
  await page.waitForFunction(()=>document.querySelector('#game').dataset.screen==='world');
  await page.locator('[data-tab="patrol"]').click();await page.screenshot({path:'output/qa-v2/patrol.png'});
  const coins=(await saved(page)).coins;await page.locator('[data-action="train"][data-arg="beaver"]').click();
  assert.equal((await saved(page)).roster.find(u=>u.species==='beaver').level,6);assert.ok((await saved(page)).coins<coins);
  await page.locator('#camp-button').click();await page.locator('[data-action="buy"][data-arg="potions"]').click();
  assert.equal((await saved(page)).potions,7);
  await page.locator('[data-action="rest"]').click();
  assert.ok((await saved(page)).roster.every(u=>u.hp===maxHP(u)));
  await page.locator('[data-tab="guide"]').click();assert.equal(await page.locator('.guide-card').count(),9);
  await page.locator('[data-action="detail"][data-arg="buffalo"]').click();assert.match(await page.locator('#detail-dialog').textContent(),/Thunder Herd/);await page.getByRole('button',{name:'Close critter details'}).click();
  await page.reload();await loaded(page);assert.equal(await page.locator('#starter-dialog').isVisible(),false);assert.equal((await saved(page)).roster.length,2);
  await page.locator('[data-action="trial"]').click();
  assert.equal(await page.locator('#game').getAttribute('data-screen'),'battle');
  await page.screenshot({path:'output/qa-v2/battle.png'});
  assert.equal(await page.locator('[data-action="battle"][data-arg="special"]').isDisabled(),true);
  await page.locator('[data-action="battle"][data-arg="guard"]').click();
  await page.waitForFunction(()=>!document.querySelector('[data-action="battle"][data-arg="attack"]').disabled);
  assert.match(await page.locator('.battle-log').textContent(),/braces and recovers/);
  await page.locator('[data-action="battle"][data-arg="swap:bobwhite"]').click();
  await page.waitForFunction(()=>!document.querySelector('[data-action="battle"][data-arg="attack"]').disabled);
  assert.match(await page.locator('.battle-health.ally').textContent(),/Bobwhite/);
  await page.locator('[data-action="retreat"]').click();
  await page.locator('#camp-button').click();await page.locator('[data-action="rest"]').click();
  await page.locator('[data-tab="trail"]').click();
  for(const [w,h,name] of [[320,568,'small-phone'],[430,932,'large-phone'],[1440,1000,'desktop']]){await page.setViewportSize({width:w,height:h});await page.screenshot({path:`output/qa-v2/${name}.png`});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);const explore=await page.locator('[data-action="explore"]').boundingBox();assert.ok(explore.y>=0&&explore.y+explore.height<h);}
  await context.close();

  // Late-game fixture exercises the final gates and battle rewards through the UI.
  const late=normalizeSave(null);chooseStarter('beaver',late);late.roster=PATROL_IDS.map(id=>makeUnit(id,15));late.team=['owl','bear','buffalo'];late.badges=['lakeside','hollow'];late.zone='ridge';late.coins=400;late.potions=9;
  const campaign=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:2,isMobile:true,hasTouch:true});
  await campaign.addInitScript(value=>{if(!localStorage.getItem('woodbadge-quest-v2'))localStorage.setItem('woodbadge-quest-v2',JSON.stringify(value));},late);
  const end=await campaign.newPage();watch(end);await end.goto('http://127.0.0.1:4173/');await loaded(end);
  await end.locator('[data-action="trial"]').click();
  for(let turn=0;turn<35;turn++){
    if(await end.locator('#battle-result').isVisible())break;
    const attack=end.locator('[data-action="battle"][data-arg="attack"]');
    await attack.waitFor({state:'visible'});await end.waitForFunction(()=>!document.querySelector('[data-action="battle"][data-arg="attack"]').disabled||document.querySelector('#battle-result').open);
    if(await end.locator('#battle-result').isVisible())break;
    const special=end.locator('[data-action="battle"][data-arg="special"]');await(special && !(await special.isDisabled())?special:attack).click();
    await end.waitForTimeout(600);
  }
  await end.locator('#battle-result').waitFor({state:'visible'});assert.match(await end.locator('#battle-result').textContent(),/Courage earned/);assert.equal((await saved(end)).badges.length,3);
  await end.screenshot({path:'output/qa-v2/badge-earned.png'});
  await end.locator('[data-action="result-trail"]').click();
  await end.locator('[data-tab="tickets"]').click();await end.locator('[data-action="claim"][data-arg="collection"]').click();assert.ok((await saved(end)).claimed.includes('collection'));await end.screenshot({path:'output/qa-v2/tickets.png'});
  await end.locator('[data-tab="trail"]').click();await end.locator('[data-action="oak"]').click();
  assert.equal(await end.locator('#encounter-name').textContent(),'PartyPoss');
  await end.locator('#attack-button').click();await end.waitForTimeout(1200);await end.screenshot({path:'output/qa-v2/maui-wali.png'});await ready(end);
  await end.evaluate(()=>{Math.random=()=>0;});await end.locator('#throw-button').press('Enter');await end.locator('#result-dialog').waitFor({state:'visible'});await end.locator('#next-button').click();
  await end.locator('#detail-dialog').waitFor({state:'visible'});assert.match(await end.locator('#detail-dialog').textContent(),/Woodland champion/);assert.ok((await saved(end)).champion);
  await end.screenshot({path:'output/qa-v2/champion.png'});
  await campaign.close();
  assert.deepEqual(allErrors,[]);
  console.log(JSON.stringify({status:'passed',checks:['starter choice','locked trails','real touch swipe catch','species-specific rewards','training','shop','rest','field guide','reload persistence','guard and swap','retreat','phone and desktop layouts','trial victory and badge','ticket claim','Great Oak unlock','Maui Wali','campaign completion'],pageErrors:allErrors},null,2));
}finally{if(allErrors.length)console.error(allErrors);await browser.close();}
